/**
 * Auto-generated by scripts/drink-images/apply-docs-upload.mjs
 * Metro requires literal require() paths per slug.
 */

export const DRINK_IMAGES: Record<string, number> = {
  'adonis': require('./adonis.webp'),
  'affogato': require('./affogato.webp'),
  'almond-horchata': require('./almond-horchata.webp'),
  'amaretto-and-soda': require('./amaretto-and-soda.webp'),
  'amaretto-sour': require('./amaretto-sour.webp'),
  'aperol-spritz': require('./aperol-spritz.webp'),
  'apple-cider-fizz': require('./apple-cider-fizz.webp'),
  'apple-martini': require('./apple-martini.webp'),
  'apricot-cooler': require('./apricot-cooler.webp'),
  'arnold-palmer': require('./arnold-palmer.webp'),
  'aviation': require('./aviation.webp'),
  'b-52': require('./b-52.webp'),
  'bahama-mama': require('./bahama-mama.webp'),
  'bamboo': require('./bamboo.webp'),
  'banana-smoothie': require('./banana-smoothie.webp'),
  'basil-lemon-fizz': require('./basil-lemon-fizz.webp'),
  'basil-lemonade': require('./basil-lemonade.webp'),
  'bay-breeze': require('./bay-breeze.webp'),
  'bellini': require('./bellini.webp'),
  'bensonhurst': require('./bensonhurst.webp'),
  'berry-basil-sparkler': require('./berry-basil-sparkler.webp'),
  'berry-blast': require('./berry-blast.webp'),
  'between-the-sheets': require('./between-the-sheets.webp'),
  'black-manhattan': require('./black-manhattan.webp'),
  'black-russian': require('./black-russian.webp'),
  'blood-orange-spritz': require('./blood-orange-spritz.webp'),
  'blue-hawaiian': require('./blue-hawaiian.webp'),
  'blue-raspberry-splash': require('./blue-raspberry-splash.webp'),
  'blueberry-lemonade': require('./blueberry-lemonade.webp'),
  'blueberry-mint-fizz': require('./blueberry-mint-fizz.webp'),
  'bobby-burns': require('./bobby-burns.webp'),
  'boulevardier': require('./boulevardier.webp'),
  'bourbon-lemonade': require('./bourbon-lemonade.webp'),
  'brandy-alexander': require('./brandy-alexander.webp'),
  'brooklyn': require('./brooklyn.webp'),
  'brown-derby': require('./brown-derby.webp'),
  'butterbeer': require('./butterbeer.webp'),
  'buttery-nipple': require('./buttery-nipple.webp'),
  'caipirinha': require('./caipirinha.webp'),
  'caipiroska': require('./caipiroska.webp'),
  'campari-spritz': require('./campari-spritz.webp'),
  'cantaloupe-cooler': require('./cantaloupe-cooler.webp'),
  'cape-codder': require('./cape-codder.webp'),
  'captain-collins': require('./captain-collins.webp'),
  'caramel-apple-smash': require('./caramel-apple-smash.webp'),
  'chai-latte': require('./chai-latte.webp'),
  'charcoal-lemonade': require('./charcoal-lemonade.webp'),
  'chi-chi': require('./chi-chi.webp'),
  'chocolate-martini': require('./chocolate-martini.webp'),
  'chocolate-milkshake': require('./chocolate-milkshake.webp'),
  'chocolate-mint-frappe': require('./chocolate-mint-frappe.webp'),
  'chrysanthemum': require('./chrysanthemum.webp'),
  'classic-margarita': require('./classic-margarita.webp'),
  'classic-martini': require('./classic-martini.webp'),
  'classic-negroni': require('./classic-negroni.webp'),
  'classic-old-fashioned': require('./classic-old-fashioned.webp'),
  'clover-club': require('./clover-club.webp'),
  'cobble-hill': require('./cobble-hill.webp'),
  'coconut-cocoa-shake': require('./coconut-cocoa-shake.webp'),
  'coconut-lime-smash': require('./coconut-lime-smash.webp'),
  'coconut-mojito': require('./coconut-mojito.webp'),
  'coconut-water-splash': require('./coconut-water-splash.webp'),
  'cold-brew-cream': require('./cold-brew-cream.webp'),
  'cold-brew-tonic': require('./cold-brew-tonic.webp'),
  'copper-brandy-sour': require('./copper-brandy-sour.webp'),
  'copper-cachaca-sour': require('./copper-cachaca-sour.webp'),
  'copper-gin-sour': require('./copper-gin-sour.webp'),
  'copper-gold-rum-sour': require('./copper-gold-rum-sour.webp'),
  'copper-pisco-sour': require('./copper-pisco-sour.webp'),
  'copper-reposado-tequila-sour': require('./copper-reposado-tequila-sour.webp'),
  'copper-scotch-whisky-sour': require('./copper-scotch-whisky-sour.webp'),
  'copper-tequila-sour': require('./copper-tequila-sour.webp'),
  'copper-vodka-sour': require('./copper-vodka-sour.webp'),
  'copper-white-rum-sour': require('./copper-white-rum-sour.webp'),
  'corpse-reviver-2': require('./corpse-reviver-2.webp'),
  'cosmopolitan': require('./cosmopolitan.webp'),
  'cranberry-apple-spritz': require('./cranberry-apple-spritz.webp'),
  'cranberry-kiss': require('./cranberry-kiss.webp'),
  'cucumber-cilantro-cooler': require('./cucumber-cilantro-cooler.webp'),
  'cucumber-cooler': require('./cucumber-cooler.webp'),
  'cucumber-lemonade': require('./cucumber-lemonade.webp'),
  'cucumber-martini': require('./cucumber-martini.webp'),
  'cucumber-mint-spritz': require('./cucumber-mint-spritz.webp'),
  'dark-and-stormy': require('./dark-and-stormy.webp'),
  'dark-mojito': require('./dark-mojito.webp'),
  'diamond-fizz': require('./diamond-fizz.webp'),
  'dirty-martini': require('./dirty-martini.webp'),
  'division-bell': require('./division-bell.webp'),
  'dragon-punch': require('./dragon-punch.webp'),
  'dragonfruit-cooler': require('./dragonfruit-cooler.webp'),
  'dry-martini': require('./dry-martini.webp'),
  'egg-cream': require('./egg-cream.webp'),
  'el-diablo': require('./el-diablo.webp'),
  'el-presidente': require('./el-presidente.webp'),
  'espresso-martini': require('./espresso-martini.webp'),
  'fig-smash': require('./fig-smash.webp'),
  'final-ward': require('./final-ward.webp'),
  'fish-house-punch': require('./fish-house-punch.webp'),
  'fizzy-orange-spice': require('./fizzy-orange-spice.webp'),
  'french-75': require('./french-75.webp'),
  'french-martini': require('./french-martini.webp'),
  'frozen-banana-daiquiri': require('./frozen-banana-daiquiri.webp'),
  'frozen-lemonade': require('./frozen-lemonade.webp'),
  'frozen-mango-smoothie': require('./frozen-mango-smoothie.webp'),
  'frozen-peach-margarita': require('./frozen-peach-margarita.webp'),
  'frozen-pina-colada': require('./frozen-pina-colada.webp'),
  'garden-gin-sour': require('./garden-gin-sour.webp'),
  'garden-reposado-tequila-sour': require('./garden-reposado-tequila-sour.webp'),
  'garden-vodka-sour': require('./garden-vodka-sour.webp'),
  'gimlet': require('./gimlet.webp'),
  'gin-buck': require('./gin-buck.webp'),
  'gin-fizz': require('./gin-fizz.webp'),
  'ginger-julep': require('./ginger-julep.webp'),
  'gingerbread-latte': require('./gingerbread-latte.webp'),
  'godfather': require('./godfather.webp'),
  'gold-rush': require('./gold-rush.webp'),
  'golden-cadillac': require('./golden-cadillac.webp'),
  'golden-fizz': require('./golden-fizz.webp'),
  'golden-turmeric-tonic': require('./golden-turmeric-tonic.webp'),
  'grape-frost': require('./grape-frost.webp'),
  'grasshopper': require('./grasshopper.webp'),
  'green-goddess-smoothie': require('./green-goddess-smoothie.webp'),
  'green-swizzle': require('./green-swizzle.webp'),
  'green-tea-lemonade': require('./green-tea-lemonade.webp'),
  'greenpoint': require('./greenpoint.webp'),
  'greyhound': require('./greyhound.webp'),
  'guava-cooler': require('./guava-cooler.webp'),
  'harbor-cognac-sour': require('./harbor-cognac-sour.webp'),
  'harbor-dark-rum-sour': require('./harbor-dark-rum-sour.webp'),
  'harbor-pisco-sour': require('./harbor-pisco-sour.webp'),
  'hemingway-daiquiri': require('./hemingway-daiquiri.webp'),
  'hibiscus-iced-tea': require('./hibiscus-iced-tea.webp'),
  'hibiscus-lime-spritz': require('./hibiscus-lime-spritz.webp'),
  'honey-citrus-punch': require('./honey-citrus-punch.webp'),
  'honey-peach-iced-tea': require('./honey-peach-iced-tea.webp'),
  'hot-buttered-rum': require('./hot-buttered-rum.webp'),
  'hot-toddy': require('./hot-toddy.webp'),
  'hotel-nacional-special': require('./hotel-nacional-special.webp'),
  'hugo-spritz': require('./hugo-spritz.webp'),
  'hunch-punch': require('./hunch-punch.webp'),
  'hurricane': require('./hurricane.webp'),
  'iced-caramel-latte': require('./iced-caramel-latte.webp'),
  'iced-matcha-latte': require('./iced-matcha-latte.webp'),
  'pineapple-lemonade': require('./pineapple-lemonade.webp'),
  'tom-collins': require('./tom-collins.webp'),
};

/** Same module as `classic-martini` registry entry — safe default when slug is missing or fails to load. */
export const FALLBACK_DRINK_IMAGE: number = DRINK_IMAGES['classic-martini'];

function normalizeImageKey(raw: string): string {
  const t = raw.trim();
  if (!t) return t;
  return t.replace(/\.(webp|png|jpg|jpeg)$/i, '');
}

/** True when a bundled WebP is registered for this `slug` or `image_path` key. */
export function hasBundledDrinkImage(slugOrPath: string): boolean {
  const key = normalizeImageKey(slugOrPath);
  if (!key) return false;
  return DRINK_IMAGES[key] != null;
}

/** Dev-only: one console line per slug (avoids hundreds of repeats while scrolling). */
const missingImageKeysLogged = new Set<string>();

function warnMissingBundledImageOnce(key: string): void {
  if (!__DEV__ || !key || missingImageKeysLogged.has(key)) return;
  missingImageKeysLogged.add(key);
  console.warn(
    `[MixMate] No bundled image for "${key}". Add assets/images/drinks/${key}.webp and a DRINK_IMAGES entry (see assets/images/drinks/README.md).`
  );
}

export function resolveDrinkImage(slug: string): number | undefined {
  const key = normalizeImageKey(slug);
  if (DRINK_IMAGES[key] != null) return DRINK_IMAGES[key];
  warnMissingBundledImageOnce(key);
  return undefined;
}
