/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ingredients` | `/ingredients`; params?: Router.UnknownInputParams; } | { pathname: `/components/DrinkCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/FeaturedCarousel`; params?: Router.UnknownInputParams; } | { pathname: `/components/FilterTabs`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useDrinks`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFavorites`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useIngredientMatcher`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useRecentlyViewed`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DetailScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/FavoritesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/IngredientsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/storage/db`; params?: Router.UnknownInputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownInputParams; } | { pathname: `/utils/types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ingredients` | `/ingredients`; params?: Router.UnknownOutputParams; } | { pathname: `/components/DrinkCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FeaturedCarousel`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FilterTabs`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useDrinks`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useFavorites`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useIngredientMatcher`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useRecentlyViewed`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/DetailScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/FavoritesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/IngredientsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/storage/db`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ingredients${`?${string}` | `#${string}` | ''}` | `/ingredients${`?${string}` | `#${string}` | ''}` | `/components/DrinkCard${`?${string}` | `#${string}` | ''}` | `/components/FeaturedCarousel${`?${string}` | `#${string}` | ''}` | `/components/FilterTabs${`?${string}` | `#${string}` | ''}` | `/components/SearchBar${`?${string}` | `#${string}` | ''}` | `/hooks/useDrinks${`?${string}` | `#${string}` | ''}` | `/hooks/useFavorites${`?${string}` | `#${string}` | ''}` | `/hooks/useIngredientMatcher${`?${string}` | `#${string}` | ''}` | `/hooks/useRecentlyViewed${`?${string}` | `#${string}` | ''}` | `/screens/DetailScreen${`?${string}` | `#${string}` | ''}` | `/screens/FavoritesScreen${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/IngredientsScreen${`?${string}` | `#${string}` | ''}` | `/storage/db${`?${string}` | `#${string}` | ''}` | `/utils/theme${`?${string}` | `#${string}` | ''}` | `/utils/types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ingredients` | `/ingredients`; params?: Router.UnknownInputParams; } | { pathname: `/components/DrinkCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/FeaturedCarousel`; params?: Router.UnknownInputParams; } | { pathname: `/components/FilterTabs`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useDrinks`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFavorites`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useIngredientMatcher`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useRecentlyViewed`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DetailScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/FavoritesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/IngredientsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/storage/db`; params?: Router.UnknownInputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownInputParams; } | { pathname: `/utils/types`; params?: Router.UnknownInputParams; };
    }
  }
}
